package opgg.api.riot;

import java.util.HashMap; 
import java.util.Map;

public class ChampionNameMapper {
    private static final Map<String, String> EN_TO_KO = new HashMap<>();

    static {
    	
    	Map<String, String> championNameKorMap = Map.ofEntries(
    		    Map.entry("Aatrox", "아트록스"),
    		    Map.entry("Ahri", "아리"),
    		    Map.entry("Akali", "아칼리"),
    		    Map.entry("Akshan", "아크샨"),
    		    Map.entry("Alistar", "알리스타"),
    		    Map.entry("Amumu", "아무무"),
    		    Map.entry("Anivia", "애니비아"),
    		    Map.entry("Annie", "애니"),
    		    Map.entry("Aphelios", "아펠리오스"),
    		    Map.entry("Ashe", "애쉬"),
    		    Map.entry("AurelionSol", "아우렐리온 솔"),
    		    Map.entry("Azir", "아지르"),
    		    Map.entry("Bard", "바드"),
    		    Map.entry("Belveth", "벨베스"),
    		    Map.entry("Blitzcrank", "블리츠크랭크"),
    		    Map.entry("Brand", "브랜드"),
    		    Map.entry("Braum", "브라움"),
    		    Map.entry("Briar", "브라이어"),
    		    Map.entry("Caitlyn", "케이틀린"),
    		    Map.entry("Camille", "카밀"),
    		    Map.entry("Cassiopeia", "카시오페아"),
    		    Map.entry("ChoGath", "초가스"),
    		    Map.entry("Corki", "코르키"),
    		    Map.entry("Darius", "다리우스"),
    		    Map.entry("Diana", "다이애나"),
    		    Map.entry("Draven", "드레이븐"),
    		    Map.entry("DrMundo", "문도 박사"),
    		    Map.entry("Ekko", "에코"),
    		    Map.entry("Elise", "엘리스"),
    		    Map.entry("Evelynn", "이블린"),
    		    Map.entry("Ezreal", "이즈리얼"),
    		    Map.entry("Fiddlesticks", "피들스틱"),
    		    Map.entry("Fiora", "피오라"),
    		    Map.entry("Fizz", "피즈"),
    		    Map.entry("Galio", "갈리오"),
    		    Map.entry("Gangplank", "갱플랭크"),
    		    Map.entry("Garen", "가렌"),
    		    Map.entry("Gnar", "나르"),
    		    Map.entry("Gragas", "그라가스"),
    		    Map.entry("Graves", "그레이브즈"),
    		    Map.entry("Gwen", "그웬"),
    		    Map.entry("Hecarim", "헤카림"),
    		    Map.entry("Heimerdinger", "하이머딩거"),
    		    Map.entry("Hwei", "흐웨이"),
    		    Map.entry("Illaoi", "일라오이"),
    		    Map.entry("Irelia", "이렐리아"),
    		    Map.entry("Ivern", "아이번"),
    		    Map.entry("Janna", "잔나"),
    		    Map.entry("JarvanIV", "자르반 4세"),
    		    Map.entry("Jax", "잭스"),
    		    Map.entry("Jayce", "제이스"),
    		    Map.entry("Jhin", "진"),
    		    Map.entry("Jinx", "징크스"),
    		    Map.entry("Kaisa", "카이사"),
    		    Map.entry("Kalista", "칼리스타"),
    		    Map.entry("Karma", "카르마"),
    		    Map.entry("Karthus", "카서스"),
    		    Map.entry("Kassadin", "카사딘"),
    		    Map.entry("Katarina", "카타리나"),
    		    Map.entry("Kayle", "케일"),
    		    Map.entry("Kayn", "케인"),
    		    Map.entry("Kennen", "케넨"),
    		    Map.entry("Khazix", "카직스"),
    		    Map.entry("Kindred", "킨드레드"),
    		    Map.entry("Kled", "클레드"),
    		    Map.entry("KogMaw", "코그모"),
    		    Map.entry("KSante", "크산테"),
    		    Map.entry("Leblanc", "르블랑"),
    		    Map.entry("LeeSin", "리 신"),
    		    Map.entry("Leona", "레오나"),
    		    Map.entry("Lillia", "릴리아"),
    		    Map.entry("Lissandra", "리산드라"),
    		    Map.entry("Lucian", "루시안"),
    		    Map.entry("Lulu", "룰루"),
    		    Map.entry("Lux", "럭스"),
    		    Map.entry("Malphite", "말파이트"),
    		    Map.entry("Malzahar", "말자하"),
    		    Map.entry("Maokai", "마오카이"),
    		    Map.entry("MasterYi", "마스터 이"),
    		    Map.entry("Milio", "밀리오"),
    		    Map.entry("MissFortune", "미스 포츈"),
    		    Map.entry("Mordekaiser", "모데카이저"),
    		    Map.entry("Morgana", "모르가나"),
    		    Map.entry("Naafiri", "나피리"),
    		    Map.entry("Nami", "나미"),
    		    Map.entry("Nasus", "나서스"),
    		    Map.entry("Nautilus", "노틸러스"),
    		    Map.entry("Neeko", "니코"),
    		    Map.entry("Nidalee", "니달리"),
    		    Map.entry("Nilah", "닐라"),
    		    Map.entry("Nocturne", "녹턴"),
    		    Map.entry("Nunu", "누누와 윌럼프"),
    		    Map.entry("Olaf", "올라프"),
    		    Map.entry("Orianna", "오리아나"),
    		    Map.entry("Ornn", "오른"),
    		    Map.entry("Pantheon", "판테온"),
    		    Map.entry("Poppy", "뽀삐"),
    		    Map.entry("Pyke", "파이크"),
    		    Map.entry("Qiyana", "키아나"),
    		    Map.entry("Quinn", "퀸"),
    		    Map.entry("Rakan", "라칸"),
    		    Map.entry("Rammus", "람머스"),
    		    Map.entry("RekSai", "렉사이"),
    		    Map.entry("Rell", "렐"),
    		    Map.entry("Renata", "레나타 글라스크"),
    		    Map.entry("Renekton", "레넥톤"),
    		    Map.entry("Rengar", "렝가"),
    		    Map.entry("Riven", "리븐"),
    		    Map.entry("Rumble", "럼블"),
    		    Map.entry("Ryze", "라이즈"),
    		    Map.entry("Samira", "사미라"),
    		    Map.entry("Sejuani", "세주아니"),
    		    Map.entry("Senna", "세나"),
    		    Map.entry("Seraphine", "세라핀"),
    		    Map.entry("Sett", "세트"),
    		    Map.entry("Shaco", "샤코"),
    		    Map.entry("Shen", "쉔"),
    		    Map.entry("Shyvana", "쉬바나"),
    		    Map.entry("Singed", "신지드"),
    		    Map.entry("Sion", "사이온"),
    		    Map.entry("Sivir", "시비르"),
    		    Map.entry("Skarner", "스카너"),
    		    Map.entry("Sona", "소나"),
    		    Map.entry("Soraka", "소라카"),
    		    Map.entry("Swain", "스웨인"),
    		    Map.entry("Sylas", "사일러스"),
    		    Map.entry("Syndra", "신드라"),
    		    Map.entry("TahmKench", "탐 켄치"),
    		    Map.entry("Taliyah", "탈리야"),
    		    Map.entry("Talon", "탈론"),
    		    Map.entry("Taric", "타릭"),
    		    Map.entry("Teemo", "티모"),
    		    Map.entry("Thresh", "쓰레쉬"),
    		    Map.entry("Tristana", "트리스타나"),
    		    Map.entry("Trundle", "트런들"),
    		    Map.entry("Tryndamere", "트린다미어"),
    		    Map.entry("TwistedFate", "트위스티드 페이트"),
    		    Map.entry("Twitch", "트위치"),
    		    Map.entry("Udyr", "우디르"),
    		    Map.entry("Urgot", "우르곳"),
    		    Map.entry("Varus", "바루스"),
    		    Map.entry("Vayne", "베인"),
    		    Map.entry("Veigar", "베이가"),
    		    Map.entry("Velkoz", "벨코즈"),
    		    Map.entry("Vex", "벡스"),
    		    Map.entry("Vi", "바이"),
    		    Map.entry("Viego", "비에고"),
    		    Map.entry("Viktor", "빅토르"),
    		    Map.entry("Vladimir", "블라디미르"),
    		    Map.entry("Volibear", "볼리베어"),
    		    Map.entry("Warwick", "워윅"),
    		    Map.entry("Wukong", "오공"),
    		    Map.entry("Xayah", "자야"),
    		    Map.entry("Xerath", "제라스"),
    		    Map.entry("XinZhao", "신 짜오"),
    		    Map.entry("Yasuo", "야스오"),
    		    Map.entry("Yone", "요네"),
    		    Map.entry("Yorick", "요릭"),
    		    Map.entry("Yuumi", "유미"),
    		    Map.entry("Zac", "자크"),
    		    Map.entry("Zed", "제드"),
    		    Map.entry("Zeri", "제리"),
    		    Map.entry("Ziggs", "직스"),
    		    Map.entry("Zilean", "질리언"),
    		    Map.entry("Zoe", "조이"),
    		    Map.entry("Zyra", "자이라")
    		);

    }

    public static String toKorean(String enName) {
        return EN_TO_KO.getOrDefault(enName, enName);
    }
}
